# Geodatenanalyse 1

## Kapitel 3: Funktionen und Berechnungen - Übung

### Aufgabe 1
#### Deine eigene Funktion
- Schreibe eine Funktion mit dem Namen *hiking()*, die Eingangsparameter für die <font color="green">zurückgelegte Strecke</font>, die dafür <font color="green">benötigte Zeit</font> und den <font color="green">Ort der Wanderung</font> hat. 

    Die Funktion sollte eine Nachricht, mit dem durchschnittlichen Lauftempo und dem Ortsnamen ausgeben. Diese könnte zum Beispiel folgendermaßen lauten:
 > " Bei unserer Wanderung in Zermatt hatten wir ein durchschnittliches Lauftempo von 3.5 km/h!" 
 

- Bei einem Tempo von unter 2 km pro Stunde soll eine zusätzliche Nachricht ausgegeben werden, mit dem Hinweis, dass die Wanderung wohl besonders anstrengend oder steil war. Nutze hierfür eine passende Wenn-Dann Bedingung. 

In [1]:
# eigene Funktion erstellen
def hiking(distance, time, location):
    speed = distance / time
    print("Bei unserer Wanderung in",str(location), 
          "hatten wir ein durchschnittliches Lauftempo von",
          speed,"km/h!")    
    if speed < 2.0:
        print("Die Wanderung muss besonders anstrengend gewesen sein!")

# Funktion aufrufen mit einer hohen Durschnittsgeschwindigkeit und einem beliebigen Ortsnamen
hiking(10.5,3,"Zermatt")

# Funktion aufrufen mit einer niedrigeren Durschnittsgeschwindigkeit und einem beliebigen Ortsnamen
hiking(6,4,"Bruchsal")

Bei unserer Wanderung in Zermatt hatten wir ein durchschnittliches Lauftempo von 3.5 km/h!
Bei unserer Wanderung in Bruchsal hatten wir ein durchschnittliches Lauftempo von 1.5 km/h!
Die Wanderung muss besonders anstrengend gewesen sein!


### Aufgabe 2
#### Erstellung von NumPy Objekten

- Erstelle mit *np.arange()* eine regelmäßige Sequenz zwischen 0 und 100, mit einem Inkrement von 4.

In [2]:
# Vergiss nicht zuerst Numpy zu laden ;)
import numpy as np

# Vektor mit regelmäßiger Sequenz
sequence = np.arange(0, 100, 4)
print(sequence)


[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


- Erstelle eine Matrix mit 10 x 20 Einträgen, welche einer regelmäßigen Sequenz beginnend bei 0 folgt.

In [3]:
# Matrix mit regelmäßige Sequenz
matrix = np.arange(0, 200).reshape(10, 20)
print(matrix)


[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]


- Lasse dir die Anzahl an Elementen (size), die Dimensionen (shape) und die Datentypen (type) beider Vektoren von oben ausgeben

In [4]:
# Ausgabe von size, shape und type
print(matrix.size)
print(matrix.shape)
print(type(matrix))


200
(10, 20)
<class 'numpy.ndarray'>


### Aufgabe 3
#### Indizierung von NumPy Objekten

- Erstelle mit Hilfe von *np.random.rand()* einen Vektor mit 1000 zufälligen Werten. Erstelle einen zweiten Vektor, welcher jeden dritten Wert des ersten Vektors enthält.

In [5]:
# Vektor mit 1000 zufälligen Werten
a = np.random.rand(1000)
print(a.shape)

# zweiter Vektor 
b = a[::3]
print(b.shape)

(1000,)
(334,)


- Forme mit Hilfe von *reshape()* den ersten Vektor von eben in eine Matrix mit 20 Zeilen und 50 Spalten um, und überprüfe die Dimensionen der erzeugten Matrix.  

In [6]:
# Umformen eines Arrays
c = a.reshape(20,50)
print(c.shape)

(20, 50)


- Lass dir nun von diesem Vektor die Werte in Spalte 5 bis 8 der dritten Zeile ausgeben, speichere außerdem die kompletten Spalten 4 und 5 in einem neuen Vektor ab.  

In [7]:
# Indizierung von Zeilen und Spalten 
print(c[3,5:8])

d = c[:,4:5]
print(d)

[0.36766058 0.96644827 0.30480584]
[[0.46732303]
 [0.15777997]
 [0.521282  ]
 [0.74255412]
 [0.09708075]
 [0.31092984]
 [0.44556291]
 [0.84633069]
 [0.44112221]
 [0.06503766]
 [0.46297561]
 [0.82861349]
 [0.03307325]
 [0.93227757]
 [0.37818498]
 [0.89850422]
 [0.44342018]
 [0.88319272]
 [0.22462503]
 [0.71322551]]


### Aufgabe 4
#### Erweiterte Funktionalität von NumPy

- Erstelle einen Vektor mit 1000 zufälligen ganzen Zahlen zwischen 0 und 100. Suche dafür in der Numpy Dokumentation (https://numpy.org/doc/stable/reference/random/legacy.html) nach einer passenden Funktion. 

In [8]:
# Vektor mit 1000 zufälligen ganzen Zahlen 
a = np.random.randint(0, 100, 1000)
print(a)

[37 89 12 21 87 78 53 69 30 89 94 74 77  4  8 18  6 81 19 79 34 99 83 48
 26 17 84 40 10 82 79 30 44 19 95 88 62  7 33 58 49 10 81 33 21  4 56 15
 55 46 97 23 96 69 16 53 19 50  3 43 45  2 19  7 53  3 66 60 26 19 95 46
  2 26 60 53 59 35 40 40 14 94 81 53 88 36 12 74 78 96 80  4 69 40 83 75
 19 61 55 13  6 29 72 25 83 38 60 56 19 16 92 73 14 52 17 94 15 58 56 58
 58 45 43 47 21  0  1  7 30 22 11 19  2 26 72 35 90 39  6 17 86 93 43 19
 26 37 89 84 22 41 55 77 86 36 38 37 97 52 86 94 52  4 79 23  4 55 97 71
 81 90  2 80 79 94 66 41 64 92 30  8 13  5 33 56 86 82 83 23  9 13 75 47
 86 26  8 94 35 13  5 54  8 68 48 62 64 43 50 46 50 27 63 87 83 67 31 17
 58  6 64 58 92 83 59 41  4 30 94 69 69 80 94  5 24 63 89 77 99 37  1  2
 83 93 25 98 83 95 97 77 39 49 45 22 77 83 46 71 71 87 76 69 50 80 67  4
 84 41 31 61 33 20 11 95 82 99 68 86 96 32 58 78 24 23 18  6 85 85 17 34
 50 61 74 29 95 92 84 14 29 33 93 48 71 83 49 47 45 21 67 71 99 66 33 83
 35 79  7 62 23 64 18  7 92 39 75 97 46 22 45 12 32

- Speichere die 5 größten Werte aus dem Vektor von eben in einem neuen Array. 

Hinweis: Nutze dafür die *sort()* Funktion und die passende Indizierung.  

In [9]:
# 5 kleinste Werte
b = np.sort(a)
c = b[-5:]
print(c)

[99 99 99 99 99]


## ENDE