# Geodatenanalyse 1

## Kapitel 3: Funktionen und Berechnungen - Übung

### Aufgabe 1
#### Deine eigene Funktion
- Schreibe eine Funktion mit dem Namen *hiking()*, die Eingangsparameter für die <font color="green">zurückgelegte Strecke</font>, die dafür <font color="green">benötigte Zeit</font> und den <font color="green">Ort der Wanderung</font> hat. 

    Die Funktion sollte eine Nachricht, mit dem durchschnittlichen Lauftempo und dem Ortsnamen ausgeben. Diese könnte zum Beispiel folgendermaßen lauten:
 > " Bei unserer Wanderung in Zermatt hatten wir ein durchschnittliches Lauftempo von 3.5 km/h!" 
 

- Bei einem Tempo von unter 2 km pro Stunde soll eine zusätzliche Nachricht ausgegeben werden, mit dem Hinweis, dass die Wanderung wohl besonders anstrengend oder steil war. Nutze hierfür eine passende Wenn-Dann Bedingung. 

In [1]:
# eigene Funktion erstellen
def hiking(distance, time, location):
    speed = distance / time
    print("Bei unserer Wanderung in",str(location), 
          "hatten wir ein durchschnittliches Lauftempo von",
          speed,"km/h!")    
    if speed < 2.0:
        print("Die Wanderung muss besonders anstrengend gewesen sein!")

# Funktion aufrufen mit einer hohen Durschnittsgeschwindigkeit und einem beliebigen Ortsnamen
hiking(10.5,3,"Zermatt")

# Funktion aufrufen mit einer niedrigeren Durschnittsgeschwindigkeit und einem beliebigen Ortsnamen
hiking(6,4,"Bruchsal")

Bei unserer Wanderung in Zermatt hatten wir ein durchschnittliches Lauftempo von 3.5 km/h!
Bei unserer Wanderung in Bruchsal hatten wir ein durchschnittliches Lauftempo von 1.5 km/h!
Die Wanderung muss besonders anstrengend gewesen sein!


### Aufgabe 2
#### Erstellung von NumPy Objekten

- Erstelle eine regelmäßige Sequenz zwischen 0 und 100, mit einem Inkrement von 4.

In [10]:
# Vergiss nicht zuerst Numpy zu laden ;)
import numpy as np

# Vektor mit regelmäßiger Sequenz
sequence = np.arange(0, 100, 4)
print(sequence)


[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


- Erstelle eine Matrix mit 10 x 20 Einträgen, welche einer regelmäßigen Sequenz beginnend bei 0 folgt.

In [25]:
# Matrix mit regelmäßige Sequenz
matrix = np.arange(0, 200).reshape(10, 20)
print(matrix)


[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]


- Lasse dir die Anzahl an Elementen (size), die Dimensionen (shape) und die Datentypen (type) beider Vektoren von oben ausgeben

In [33]:
# Ausgabe von size, shape und type
print(matrix.size)
print(matrix.shape)
print(type(matrix))


200
(10, 20)
<class 'numpy.ndarray'>


### Aufgabe 3
#### Indizierung von NumPy Objekten

- Erstelle einen Vektor mit 1000 zufälligen Werten. Erstelle einen zweiten Vektor, welcher jeden dritten Wert des ersten Vektors enthält.

In [39]:
# Vektor mit 1000 zufälligen Werten
a = np.random.rand(1000)
print(a.shape)

# zweiter Vektor 
b = a[::3]
print(b.shape)

(1000,)
(334,)


- Forme mit Hilfe von *reshape()* den ersten Vektor von eben in eine Matrix mit 20 Zeilen und 50 Spalten um, und überprüfe die Dimensionen der erzeugten Matrix.  

In [48]:
# Umformen eines Arrays
c = a.reshape(20,50)
print(c.shape)

(20, 50)


- Lass dir nun von diesem Vektor die Werte in Spalte 5 bis 8 der dritten Zeile ausgeben, speichere außerdem die kompletten Spalten 4 und 5 in einem neuen Vektor ab.  

In [65]:
# Indizierung von Zeilen und Spalten 
print(c[3,5:8])

d = c[:,4:5]
print(d)

[0.5649049  0.42533347 0.86277082]
[[0.48485979]
 [0.80326067]
 [0.31313574]
 [0.89090019]
 [0.82343455]
 [0.36023873]
 [0.56719752]
 [0.07927027]
 [0.61170708]
 [0.1624545 ]
 [0.1230773 ]
 [0.13357249]
 [0.61076329]
 [0.91036407]
 [0.15367426]
 [0.25064625]
 [0.34323295]
 [0.93028659]
 [0.20693875]
 [0.55381931]]


### Aufgabe 4
#### Erweiterte Funktionalität von NumPy

- Erstelle einen Vektor mit 1000 zufälligen ganzen Zahlen zwischen 0 und 100. 

In [66]:
# Vektor mit 1000 zufälligen ganzen Zahlen 
a = np.random.randint(0, 100, 1000)
print(a)

[28 15  4 53 48 89 49 27 23 70 84 27 33 96 26 96 72  8 92 36 39 18 95 95
 34 74 54 38 78 45 96 85 15 21 37 61 92 79 48 98 90 77 63 41 55 49 95 99
 41 63 67 19 13 50 93 36 47  2 99 47 23 85 34 95 77  8 43 92 59 10 25 14
 67  6 49 73 69 76 35 59 86  1  1 46 96 84 95 10 70 58 61 41 85 37 66 59
 24 13 42 95 61 50 31 98 90 16 84  6 57 11 13 13 46  5 58 80 18 43 48 27
 12 51 13 14 97 25 11 52 83 62 68 89 21 71 34  5 82 19 98 61 82 84 69 52
 55 70 56 78 88 61 22 62 84 25 15 90 54 72 53  3 55 66 74 40 45 90 90 54
 44 40 59 83 74 30 88 99 51 35 74 86 90 32  0 17 66  8 35 60 65 52 41 41
 27 85 40 12 89 44 88 30 31 95 82 42 17 74 67 74 51 56 93 49 71 43 57 19
 67 89 39 68 98 51 69 21 47 62 96 47 17 77 23 87 69 53 37  2 27 48 66 44
 12 79 11 70 23 56  7 16 19 14 48 11 17 88 98 95 54 53 15 42 73 99 19 77
 29  0 56 41 97 53 30 75 64 29 68 38 16 30 73 79 52 36 31 46 52 58 40 94
 52 61  5 42 42 29 48 74 78 64 35 49 39  2 10 15 75 53 77 60 29 76 18 76
 27 59 24 90 28 59  1  0 65 64 90 97 64 52 76 41 83

- Speichere die 5 größten Werte aus dem Vektor von eben in einem neuen Array. 

Hinweis: Nutze dafür die *sort()* Funktion und die passende Indizierung.  

In [75]:
# 5 kleinste Werte
b = np.sort(a)
c = b[-5:]
print(c)

[99 99 99 99 99]


## ENDE