#  Geospatial Data Analysis I

## Chapter 3: Functions and calculations - exercises

### Exercise 1
#### for-loop and if-else statements

- create two lists with 5 elements each. One should contain names of specific rocks, the other names of minerals to be found in the corresponding rocks. Make that you have covered all three different typs of rocks (i.e. igneous, metamorphic and sedimentary rocks). 

> rocks = ["granite", "basalt", ...]

> minerals = ["feldspar", "olivine", ...]

- then use a for-loop to create output messages for each rock-mineral pair. For example: 

> "Granite contains feldspar." and so on. 

- hint: to set up the identifier you can e.g. use the functions *range()* and the *len()* command. 

In [11]:
# create lists
rocks = ["granite", "basalt", "eklogit", "sandstone", "marble"]
minerals = ["feldspar", "olivine", "granat", "quartz", "calcite"]

# for-loop in general form with [i] and sequence
for i in range(len(rocks)): 
    print (rocks[i] + " contains "+ minerals[i]+ ".")

# for-loop option 2 with form "item in list" --> can only take one item, here as we have two items: minerals and rocks
# for rocks, mineral in rocks, mineral: 
#    print(rock + " contains "+ mineral + ".")

granite contains feldspar.
basalt contains olivine.
eklogit contains granat.
sandstone contains quartz.
marble contains calcite.


- extend the for-loop from above with an if-else statement regarding the type of rock, and adapt the output message accordingly. 

- in case you are unsure about the required structure of the code, make some notes in "pseudocode" first. That is a sequence of functionalities, but without using exact Python syntax from the beginning, e.g:   

> if rock == granite or basalt, 

> then message == "rock X contains mineral X and is an igneous rock."

> if rock == ... 

In [12]:
# for-loop with if-else statement 
for i in range(len(rocks)): 

    if rocks[i] == 'granite' or rocks [i] == 'basalt': # first tpye of rock, IMPORTANT: index [i] of rocks so that each spcific element os tested within the loop. 
        print (rocks[i] + " contains "+ minerals[i]+ " and is an igneous rock.")

    elif rocks[i] == 'eklogit' or rocks[i] == 'marble': # second type of rock
        print (rocks[i] + " contains "+ minerals[i]+ " and is an metamorphic rock.")

    elif rocks[i] == 'sandstone': # third type of rock 
        print (rocks[i] + " contains "+ minerals[i]+ " and is an sedimentary rock.")
    
    else: 
        print ('I do not know this rock') # as final option in case something unforseen happens. 


granite contains feldspar and is an igneous rock.
basalt contains olivine and is an igneous rock.
eklogit contains granat and is an metamorphic rock.
sandstone contains quartz and is an sedimentary rock.
marble contains calcite and is an metamorphic rock.


### Exercise 2
#### Creating NumPy Objects

- use *np.arange()* to create a continuous sequence of numbers from 0 to 100, with an increment of 4.

In [13]:
# don't forget to import numpy first  ;)
import numpy as np

# create an array
sequence = np.arange(0, 100, 4)
print(sequence)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


- create a matrix with 10 by 20 entries, which follow a continuous sequence starting with 0.

In [14]:
# matrix with a continuous sequence
matrix = np.arange(0, 200).reshape(10, 20)
print(matrix)


[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]


- check the number of elements (size), dimensions (shape) and data type (type) of both variables from above

In [15]:
# print size, shape and type
print(matrix.size)
print(matrix.shape)
print(type(matrix))


200
(10, 20)
<class 'numpy.ndarray'>


### Exercise 3
#### Indices of NumPy objects

- create a vector with 1000 random numbers with the help of *np.random.rand()*. In addition, create a second vector that contains every third value of the first vector. 

In [16]:
# array with 1000 random values
a = np.random.rand(1000)
print(a.shape)

# second array 
b = a[::3]
print(b.shape)

(1000,)
(334,)


- convert the first vector from above into a matrix with 20 lines and 50 columns using *reshape()*, and check the dimensions of the newly created matrix.  

In [17]:
# conversion of an array
c = a.reshape(20,50)
print(c.shape)

(20, 50)


- from this vector display the values in columns 5 to 8 of the third line, and save the entire columns 4 and 5 into a new vector.   

In [18]:
# indices of lines and rows 
print(c[3,5:8])

d = c[:,4:5]
print(d)

[0.74645311 0.4377456  0.42827352]
[[0.12807191]
 [0.07990641]
 [0.70021525]
 [0.31167087]
 [0.98744221]
 [0.5882549 ]
 [0.83528034]
 [0.6055579 ]
 [0.56244571]
 [0.66564992]
 [0.1811566 ]
 [0.62831195]
 [0.3798108 ]
 [0.36520985]
 [0.41375259]
 [0.42715319]
 [0.99405589]
 [0.43948697]
 [0.7269229 ]
 [0.33460316]]


### Exercise 4
#### Other functionalities in NumPy

- creat an array with 1000 random integer numbers between 0 and 100. Look for a purpose-built function in the NumPy documentation: https://numpy.org/doc/stable/reference/random/legacy.html 

In [19]:
# array with random integer values 
a = np.random.randint(0, 100, 1000)
print(a)

[74 41 89 77 65 48 31 92 34 72 67 66 13 74 45  4  7 30 96 69 40 59 16 39
 27 63 21 58 58 29 34 25 30 80 34 31 36 78 96 86 12 83 94 81 80 35 66 12
 77 94 78 60 77 41 70 63 63 78 82 75 23 50 64 38 78 43 52 43 42 39 76 30
 60  2 44 17 26 14 79 78 40 89 44 20 65 93 47 89 41 83 80 96 63  6 63 52
 35  3 33 28 43  7 16 44 22 36 59 89 47 87 87 33 41 67  8 35 88 88  2 70
 68 14 64 43 72 74 52 83 75 92 18 47 64 78 80 33 92 99  4 47 92 48 60 20
 57 24 22  0 28 50 40 84 58 28 64 95 30 62 88 98 99 24 87  9 83 11 71 67
 56 47 36  2 82 97 85 11 12  2 27 46 25 35 11 54  1 40 51 80 69 59 55  3
 41 99 19  2 12 67  4 43 19 59 64 71 56 19 80 53 82 59 40 25 49 89 33 36
 83 88 58 92 98 86 17 21 81 45 48 58 85 98  7  7 87 54 47 61 56 30 19  0
 69 22 27 27 88  8 70 87 33 35 60 37 51 33 54 86 19 25 89 39 52 15 54 67
 33 10 62 67 50 26 36 64 35 70 52 65  5 56 44 37 49 39 85 68 56 74 18 62
  0 53 65 46 34  2 19 65 58 53 72 32 24 39 39 78 76 90 23 43 16 37 97 11
 57 14 69 86 25 63 47 56 28 32  9 62 62 59 31 84 93

- save the 5 highest numbers from this array into a new array. 

Hint: Use the *sort()* function and appropriate indices.

In [20]:
# 5 highest numbers
b = np.sort(a)
c = b[-5:]
print(c)

[99 99 99 99 99]


### Exercise 5
#### Your own function
- Write a function with the name *hiking()*, with input parameters for the <font color="green">covered distance</font>, the <font color="green">time spent</font> and the <font color="green">location of the hike</font>. 

    The function is supposed to print a message with the average speed and the location. For example:
 > " For our hike in Zermatt we had an average speed of 3.5 km/h!" 
 

- If the speed is lower than 2 km/h there should be an additional message, with a note that the hike was apparently quite exhausting or the route quite steep. Use an if-else statement to implement this. 


In [21]:
# your own function 
def hiking(distance, time, location):
    speed = distance / time
    print("For our hike in",str(location), 
          "we had an average speed of",
          speed,"km/h!")    
    if speed < 2.0:
        print("This must have been exhausting!")

# call the function with a high average speed and chose a location 
hiking(10.5,3,"Zermatt")

# call the function with a low average speed and chose a location
hiking(6,4,"Bruchsal") 

For our hike in Zermatt we had an average speed of 3.5 km/h!
For our hike in Bruchsal we had an average speed of 1.5 km/h!
This must have been exhausting!


## END