# Geodatenanalyse 1


## Lösung: Termin 3 - Block 1

## Einführung in *NumPy*

In [1]:
import numpy as np

## Übung 1

Erstellung von Objekten:

- **Aufgabe 1**: Erstelle eine regelmäßige Sequenz zwischen 0 und 1000, mit einem Inkrement von 4.
- **Aufgabe 2**: Erstelle eine Matrix mit 10 x 20 Einträgen, welche einer regelmäßigen Sequenz folgt.
- **Aufgabe 3**: Erstelle eine Matrix mit 100 x 100 zufälligen Einträgen zwischen 0 und 1. Schreibe alle Werte, die über 0.35 liegen, in einen Vektor.

In [2]:
# Aufgabe 1

sequence = np.arange(0, 1004, 4)
print(sequence)

[   0    4    8   12   16   20   24   28   32   36   40   44   48   52
   56   60   64   68   72   76   80   84   88   92   96  100  104  108
  112  116  120  124  128  132  136  140  144  148  152  156  160  164
  168  172  176  180  184  188  192  196  200  204  208  212  216  220
  224  228  232  236  240  244  248  252  256  260  264  268  272  276
  280  284  288  292  296  300  304  308  312  316  320  324  328  332
  336  340  344  348  352  356  360  364  368  372  376  380  384  388
  392  396  400  404  408  412  416  420  424  428  432  436  440  444
  448  452  456  460  464  468  472  476  480  484  488  492  496  500
  504  508  512  516  520  524  528  532  536  540  544  548  552  556
  560  564  568  572  576  580  584  588  592  596  600  604  608  612
  616  620  624  628  632  636  640  644  648  652  656  660  664  668
  672  676  680  684  688  692  696  700  704  708  712  716  720  724
  728  732  736  740  744  748  752  756  760  764  768  772  776  780
  784 

In [3]:
# Aufgabe 2

matrix = np.arange(0, 400, 2)
matrix = matrix.reshape(10, 20)
print(matrix.shape)
print(matrix)

(10, 20)
[[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
   36  38]
 [ 40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74
   76  78]
 [ 80  82  84  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114
  116 118]
 [120 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154
  156 158]
 [160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192 194
  196 198]
 [200 202 204 206 208 210 212 214 216 218 220 222 224 226 228 230 232 234
  236 238]
 [240 242 244 246 248 250 252 254 256 258 260 262 264 266 268 270 272 274
  276 278]
 [280 282 284 286 288 290 292 294 296 298 300 302 304 306 308 310 312 314
  316 318]
 [320 322 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354
  356 358]
 [360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
  396 398]]


In [4]:
# Aufgabe 3

matrix = np.random.rand(10000)
matrix

array([0.03193599, 0.11334271, 0.0075603 , ..., 0.14268974, 0.13250866,
       0.5443552 ])

In [5]:
idx = (matrix > 0.35)
idx

array([False, False, False, ..., False, False,  True])

In [6]:
vector = matrix[idx]
print(vector.size)
print(vector)

6527
[0.67179603 0.35282412 0.88758417 ... 0.41991448 0.69512218 0.5443552 ]


## Übung 2

Indizierung:

- **Aufgabe 1**: Erstelle einen Vektor mit 1000 zufälligen Werten. Erstelle einen zweiten Vektor, welcher jeden dritten Wert des ersten Vektors enthält.
- **Aufgabe 2**: Erstelle eine 10 x 10 Matrix mit zufälligen Werten. Setze alle Werte unter 0.5 ins Negative.
- **Aufgabe 3**: Betrachten wir einen gegebenen Vektor, wie addiert man 1 zu jedem Element, das durch einen zweiten Vektor indiziert wird (Vorsicht bei wiederholten Indizes)?
- **Aufgabe 4**: Erstelle zwei Vektoren: Einer mit 20 zufälligen Integern zwischen 0 und 10, einer mit 10 zufälligen Werten zwischen 0 und 5. Entferne alle Werte vom ersten Vektor, welche auch im zweiten Vektor enthalten sind.

In [7]:
# Aufgabe 1

a = np.random.rand(1000)
print(a.shape)
b = a[::3]
print(b.shape)

(1000,)
(334,)


In [8]:
# Aufgabe 2

A = np.random.rand(10, 10)
print(A)

bol = (A < 0.5)

A[bol] *= -1
print(A)

[[0.81270715 0.53371504 0.82572185 0.57876776 0.13901943 0.82246569
  0.34749494 0.14017262 0.61942318 0.28332276]
 [0.97340772 0.78135797 0.38920387 0.00244251 0.15692765 0.62036157
  0.32637747 0.33816481 0.24102586 0.79865218]
 [0.67404794 0.29706968 0.38161595 0.81050654 0.36873676 0.80231839
  0.83903781 0.5297053  0.35011851 0.64478138]
 [0.88945916 0.27501237 0.01239691 0.78818591 0.06307007 0.72915639
  0.81481109 0.57451577 0.48844623 0.59707496]
 [0.78249902 0.31063522 0.50822193 0.50257382 0.09259664 0.13408854
  0.86293405 0.64397989 0.60174608 0.11538499]
 [0.78999701 0.06983945 0.10853413 0.20686897 0.77976511 0.15925553
  0.12789272 0.16249816 0.7285308  0.24636176]
 [0.76394053 0.36733503 0.92950935 0.85137559 0.04275114 0.35625238
  0.19398418 0.58617772 0.5537378  0.78816702]
 [0.23031436 0.9643857  0.81421339 0.55261972 0.72920942 0.8715166
  0.14830418 0.78014663 0.96244401 0.64380337]
 [0.18518315 0.58860084 0.83800388 0.55358328 0.31779647 0.42786163
  0.69602993 

In [9]:
# Aufgabe 3

# erstelle zufällige Werte
a = np.random.rand(20)
print(a)
# erstelle zufällige Indices
idx = np.random.randint(0, 20, 10)
# doppelte Werte vermeiden
idx = np.unique(idx)

# Rechenoperation durchführen
b = np.copy(a)
b[idx] += 1
print(b)

# checke die Berechnung
print(b - a)

[0.65823157 0.8250234  0.31072779 0.49576942 0.86196523 0.38264842
 0.84654189 0.33150655 0.73282205 0.70325056 0.83137309 0.03115394
 0.96758184 0.78513474 0.16814445 0.53470078 0.78867511 0.4338143
 0.7215712  0.5267324 ]
[1.65823157 1.8250234  0.31072779 1.49576942 0.86196523 0.38264842
 1.84654189 0.33150655 0.73282205 0.70325056 0.83137309 0.03115394
 0.96758184 1.78513474 0.16814445 0.53470078 1.78867511 1.4338143
 0.7215712  0.5267324 ]
[1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0.]


In [10]:
# Aufgabe 4

# erstelle Werte
a = np.random.randint(0, 10, 20)
print(a)
b = np.random.randint(0, 5, 10)
print(b)

idx = np.isin(a, b)
print(idx)

c = a[~idx]
print(c)

[2 1 6 5 5 7 2 4 9 5 2 6 5 9 6 4 1 6 1 6]
[1 1 4 4 4 0 3 0 3 2]
[ True  True False False False False  True  True False False  True False
 False False False  True  True False  True False]
[6 5 5 7 9 5 6 5 9 6 6 6]


## Übung 3

Erweiterte Funktionalität:

- **Aufgabe 1**: Erstelle einen Vektor mit 1000 zufälligen ganzen Zahlen zwischen 0 und 100. Finde den häufigsten Wert in diesem Vektor.
- **Aufgabe 2**: Erstelle einen Vektor mit 10 Werten der Sinusfunktion im Intervall [0 und $\pi$]. Erweitere diesen Vektor um das Zehnfache durch lineare Interpolation.

- **Aufgabe 3**: Erstelle einen Vektor mit 1000 zufälligen Werten. Berechne den gleitenden Durchschnitt über 10 Werte.

In [12]:
# Aufgabe 1

a = np.random.randint(0, 100, 1000)

# zähle jeden Wert
counts = np.bincount(a)
print(counts)
idx = np.argmax(counts)
print(counts[idx])

[ 8 15 12 10  8 12 11  6  6 16 13 14 11  9  7 17 10  8 12 11 10  7 15 11
  9 12  6  9  8 11 12  9  9 11 10 14 11 10 12  9 10  8 10  6 13 14 13  9
  8  5 12  8 11 10 12 10  9  7  9  7 11  6  6  4 14  9 11 12 10  9  9  9
  6 12 12  2  6 10  7 11 11  9  6 11  7 17  9  9 10 12  9 12  8  5 17 10
 10 18 10 12]
18


In [13]:
# Aufgabe 2

x1 = np.linspace(0, np.pi, 10)
y1 = np.sin(x1)

# x-Vektor generieren
x2 = np.linspace(0, np.pi, 40)

# Werte interpolieren
y2 = np.interp(x2, x1, y1)
print(y2)

[0.00000000e+00 7.89277254e-02 1.57855451e-01 2.36783176e-01
 3.15710902e-01 3.88292061e-01 4.57699938e-01 5.27107815e-01
 5.96515692e-01 6.59959748e-01 7.11476162e-01 7.62992576e-01
 8.14508990e-01 8.66025404e-01 8.93436715e-01 9.20848027e-01
 9.48259338e-01 9.75670649e-01 9.84807753e-01 9.84807753e-01
 9.84807753e-01 9.84807753e-01 9.75670649e-01 9.48259338e-01
 9.20848027e-01 8.93436715e-01 8.66025404e-01 8.14508990e-01
 7.62992576e-01 7.11476162e-01 6.59959748e-01 5.96515692e-01
 5.27107815e-01 4.57699938e-01 3.88292061e-01 3.15710902e-01
 2.36783176e-01 1.57855451e-01 7.89277254e-02 1.22464680e-16]


In [14]:
# Aufgabe 3
a = np.random.rand(1000)

# eine Funktion für den gleitenden Durchschnitt
def runningMean(x, N):
    y = np.zeros((len(x),))
    for ctr in range(len(x)):
         y[ctr] = np.sum(x[ctr:(ctr+N)])
    return y/N

# Funktion anwenden
b = runningMean(a, 10)
print(b)

[0.5949813  0.54723056 0.59222348 0.58291957 0.53374158 0.52737148
 0.48718924 0.45396663 0.48492874 0.42419789 0.48147516 0.52773847
 0.51567119 0.59433431 0.54685359 0.61330611 0.62992102 0.68529681
 0.65952781 0.64207764 0.61493881 0.53830444 0.50581799 0.41736447
 0.45169664 0.37731826 0.36073439 0.36861338 0.36810146 0.37001331
 0.42415795 0.5024514  0.48456577 0.56887741 0.59194563 0.58307069
 0.59073144 0.55676027 0.58421246 0.6096875  0.52090212 0.48902898
 0.50517654 0.47667556 0.48269065 0.47459789 0.47701744 0.4120524
 0.37068657 0.41496148 0.42874055 0.43055784 0.37949297 0.36284168
 0.35533501 0.38305347 0.34983383 0.39915149 0.43287463 0.34966613
 0.4249913  0.37634895 0.44943282 0.45057589 0.40228628 0.4547799
 0.49851911 0.4781663  0.42912085 0.49969033 0.47566522 0.56538378
 0.49505377 0.54449015 0.54912288 0.49560353 0.45609796 0.46709021
 0.52913037 0.49857338 0.48821042 0.45139387 0.48921222 0.42817236
 0.43187723 0.40552857 0.43691811 0.39867931 0.38069599 0.396057

## ENDE