<img src="kit_logo.jpg" width="200" height="200" align="right"/>

##### Lehrstuhl für Analytics and Statistics (IOR)
##### Prof. Dr. Oliver Grothe
##### SS 2020


# Multivariate Verfahren
## Übung 2

#### Aufgabe 2
Gegeben seien Vektoren $x = (1, -2, 3,)'$ und $y = (3, 2, 1)'$.
* Berechnen Sie das Tensorprodukt $xy'$.

* Berechnen Sie nun $det(xy')$.

* Wie erklären Sie sich das Ergebnis?

In [1]:
import numpy as np
from numpy import linalg as la

In [3]:
X = np.matrix([[1,-2,3]]).T
X

matrix([[ 1],
        [-2],
        [ 3]])

In [5]:
Y = np.array([[3,2,1]]).T
Y

array([[3],
       [2],
       [1]])

das Tensorprodukt $xy'$ (Matrixberechnung)

In [6]:
np.matmul(X, Y.T)


matrix([[ 3,  2,  1],
        [-6, -4, -2],
        [ 9,  6,  3]])

In [7]:
x = np.array([1,-2,3])
y = np.array([3,2,1])

das Tensorprodukt $xy'$ (Vektorberechnung)

In [9]:
t=np.tensordot(x,y,0)
#np.dot(X,Y.T)
t

array([[ 3,  2,  1],
       [-6, -4, -2],
       [ 9,  6,  3]])

$det(xy')$

In [10]:
d = la.det(t)
d

0.0

#### Aufgabe 3
Gegeben sei die Matrix $A = \left(\begin{matrix} 1 & 2 \\ 2 & 1 \end{matrix}\right)$.

* Berechnen Sie die Spur der Matrix $A$.
* Berechnen Sie die Determinante von $A$.
* Berechnen Sie die Eigenwerte $\lambda_1$ und $\lambda_2$ Eigenvektoren von $A$. 
* Überprüfen Sie, ob $det(A) = \lambda_1\lambda_2$ und $Spur(A) = \lambda_1 + \lambda_2$.

In [11]:
A = np.array([[1,2],[2,1]]) 
A

array([[1, 2],
       [2, 1]])

$Spur(A)$

In [12]:
sp = np.trace(A) 
sp

2

$det(A)$

In [13]:
de = la.det(A) 
de

-2.9999999999999996

In [15]:
[v,w]=la.eigh(A)
lambda_1 = v[0]
lambda_2 = v[1]
print('die Eigenwerte:',lambda_1,',' ,lambda_2)

die Eigenwerte: -1.0 , 3.0


$det(A) = \lambda_1\lambda_2?$ 

In [16]:

lambda_1*lambda_2

-3.0

$Spur(A) = \lambda_1 + \lambda_2?$

In [17]:
lambda_1+lambda_2

2.0

#### Aufgabe 4
Gegeben seien folgende Matrizen:

$X = \left(\begin{matrix} \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{3}} & \frac{1}{\sqrt{6}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{3}} &\frac{1}{\sqrt{6}} \\ 0 & \frac{1}{\sqrt{3}} & -\frac{2}{\sqrt{6}} \end{matrix}\right)$,
$W = \left(\begin{matrix} 3 & 1 & 0 \\ 1 & 3 & 0 \\ 0 & 0 & \frac{2}{5} \end{matrix}\right)$.

* Bestimmen Sie $W^{-1}$.
* Berechnen Sie $XX'$. Wie nennt man eine solche Matrix $X$?
* Wie lautet $X^{-1}$?


In [18]:
X = np.array([[1/np.sqrt(2),1/np.sqrt(3), 1/np.sqrt(6)], [1/np.sqrt(2),-1/np.sqrt(3), -1/np.sqrt(6)], [0,1/np.sqrt(3), -2/np.sqrt(6)]]) 
X

array([[ 0.70710678,  0.57735027,  0.40824829],
       [ 0.70710678, -0.57735027, -0.40824829],
       [ 0.        ,  0.57735027, -0.81649658]])

In [19]:
W = np.array([[3,1,0],[1,3,0],[0,0,2/5]])
W

array([[3. , 1. , 0. ],
       [1. , 3. , 0. ],
       [0. , 0. , 0.4]])

$W^{-1}$

In [20]:
W_i = la.inv(W)
W_i

array([[ 0.375, -0.125,  0.   ],
       [-0.125,  0.375,  0.   ],
       [ 0.   ,  0.   ,  2.5  ]])

$XX'$

In [23]:
M = np.matmul(X,X.T)
M

array([[ 1.00000000e+00, -2.49570864e-16,  4.58633852e-19],
       [-2.49570864e-16,  1.00000000e+00, -4.58633852e-19],
       [ 4.58633852e-19, -4.58633852e-19,  1.00000000e+00]])

In [22]:
X.dot(X.T)

array([[ 1.00000000e+00, -2.49570864e-16,  4.58633852e-19],
       [-2.49570864e-16,  1.00000000e+00, -4.58633852e-19],
       [ 4.58633852e-19, -4.58633852e-19,  1.00000000e+00]])

$X^{-1}$

In [19]:
X_i = la.inv(X)
X_i

array([[ 0.70710678,  0.70710678,  0.        ],
       [ 0.57735027, -0.57735027,  0.57735027],
       [ 0.40824829, -0.40824829, -0.81649658]])

#### Aufgabe 5
Gegeben sei die Datenmatrix 
$X = \left(\begin{matrix} -2 & -1 & 0 \\ 2 & 1 & 0 \\ 0 & -1 & 3 \\ 4 & 1 & 1 \end{matrix}\right)$ mit vier Beobachtungen von drei Variablen. 

Die empirischen Standardabweichungen der Variablen sind $\sigma_1=\sqrt{\frac{20}{3}}$,  $\sigma_2=\sqrt{\frac{4}{3}}$, und $\sigma_3=\sqrt{2}$.

* Standardisieren Sie die Daten $X$ mit Hilfe der Centering-Matrix.
* Wie berechnet sich die empirische Korrelationsmatrix?

In [24]:
X = np.array([[-2,-1,0],[2,1,0],[0,-1,3],[4,1,1]])
X

array([[-2, -1,  0],
       [ 2,  1,  0],
       [ 0, -1,  3],
       [ 4,  1,  1]])

standardisieren $X$ elementweise 

In [25]:
mw = np.diag(np.mean(X, axis=0))
stdw = np.diag(np.std(X, axis=0))
Z=(X-np.ones(X.shape).dot(mw)).dot(la.inv(stdw))
Z

array([[-1.34164079, -1.        , -0.81649658],
       [ 0.4472136 ,  1.        , -0.81649658],
       [-0.4472136 , -1.        ,  1.63299316],
       [ 1.34164079,  1.        ,  0.        ]])

standardisieren $X$ mit Hilfe der Centering-Matrix

In [26]:
(X-(1/X.shape[0])*(np.ones((X.shape[0],1))).dot(np.ones((X.shape[0],1)).T.dot(X))).dot(la.inv(stdw))

array([[-1.34164079, -1.        , -0.81649658],
       [ 0.4472136 ,  1.        , -0.81649658],
       [-0.4472136 , -1.        ,  1.63299316],
       [ 1.34164079,  1.        ,  0.        ]])

standardisieren $X$ mit Hilfe der *`zscore`* Funktion.

In [27]:
from scipy import stats
stats.zscore(X) 

array([[-1.34164079, -1.        , -0.81649658],
       [ 0.4472136 ,  1.        , -0.81649658],
       [-0.4472136 , -1.        ,  1.63299316],
       [ 1.34164079,  1.        ,  0.        ]])