<img src="KITlogo_1c_deutsch-eps-converted-to.pdf" width="200" height="200" align="right"/>

##### Lehrstuhl für Analytics and Statistics (IOR)
##### Prof. Dr. Oliver Grothe
##### WS 2021

# Analyse multivariater Daten
## Übung 12


In [10]:
# imports
import pandas as pd # data structures
import numpy as np # large, multi-dimensional arrays and matrices
import matplotlib.pyplot as plt # plotting library
from mpl_toolkits.mplot3d import Axes3D # 3d plots

import statsmodels.api as sm 
import statsmodels.formula.api as smf
import seaborn as sns

from sklearn.linear_model import LinearRegression


%matplotlib notebook

 Daten aus Skript

In [56]:
A=np.array([[3,2400,1,0],[2, 2750, 1, 1 ],[3, 2100, 0, 1],[5, 2510, 0, 1 ],[7, 2820, 1, 0 ],[1, 2450, 1, 0 ],[4, 2600, 1, 1 ],[4, 2500, 1, 0 ],[5, 2500, 1, 1 ],[4, 2640, 0, 1 ],[8, 2250, 0, 1 ],[2, 2900, 1, 1 ],[6, 2800, 0, 0 ],[1 ,2000, 1, 1 ],[1, 3000, 1, 0 ],[4, 1800, 0, 0 ],[3, 2380, 1, 1 ],[4, 2345, 1, 1],[11, 1970, 0, 0 ],[3, 2190, 0, 0 ]])
A
c=np.array([1,1,1,0,0,1,1,1,1,1,0,1,0,1,1,0,1,1,0,1])
A

array([[   3, 2400,    1,    0],
       [   2, 2750,    1,    1],
       [   3, 2100,    0,    1],
       [   5, 2510,    0,    1],
       [   7, 2820,    1,    0],
       [   1, 2450,    1,    0],
       [   4, 2600,    1,    1],
       [   4, 2500,    1,    0],
       [   5, 2500,    1,    1],
       [   4, 2640,    0,    1],
       [   8, 2250,    0,    1],
       [   2, 2900,    1,    1],
       [   6, 2800,    0,    0],
       [   1, 2000,    1,    1],
       [   1, 3000,    1,    0],
       [   4, 1800,    0,    0],
       [   3, 2380,    1,    1],
       [   4, 2345,    1,    1],
       [  11, 1970,    0,    0],
       [   3, 2190,    0,    0]])

In [57]:
select=np.where(c==1,True,False)
group1=A[select]
group1
select1=np.where(c==0,True,False)
group2=A[select1]
group2


array([[   5, 2510,    0,    1],
       [   7, 2820,    1,    0],
       [   8, 2250,    0,    1],
       [   6, 2800,    0,    0],
       [   4, 1800,    0,    0],
       [  11, 1970,    0,    0]])

In [58]:
S_1=np.cov(group1,rowvar=False)
S_2=np.cov(group2,rowvar=False)
n_1=group1.shape[0]
n_2=group2.shape[0]

In [59]:
W=n_1*S_1+n_2*S_2

In [60]:
x_queer1=np.mean(group1,axis=0)
x_queer2=np.mean(group2,axis=0)
x_queer2

array([6.83333333e+00, 2.35833333e+03, 1.66666667e-01, 3.33333333e-01])

In [61]:
d=np.dot(np.linalg.inv(W),x_queer2-x_queer1)
d

array([ 6.62149813e-02,  7.61181791e-05, -1.87183985e-01, -9.92428384e-02])