<img src="kit_logo.jpg" width="200" height="200" align="right"/>

##### Lehrstuhl für Analytics and Statistics (IOR)
##### Prof. Dr. Oliver Grothe
##### WS 2021

# Analyse multivariater Daten
## Übung 2

#### Rechnerubung: 
Laden Sie die beiden Matrizen A und B aus Ilias herunter.
    Berechnen Sie:     $A^2$, $A^{10}$, $A · B$, $(A · B)^{−1}$, $spur(A)$, $det(A)$

Load $A$ and $B$

In [1]:
import pandas as pd
import numpy as np
A=np.array(pd.read_csv('A.csv', sep=';',header=None))
B=np.array(pd.read_csv('B.csv', sep=';',header=None))
print('Shape of A: ',A.shape)
print('Shape of B: ',B.shape)

Shape of A:  (1000, 1000)
Shape of B:  (1000, 1000)


Calculate $A^2$


In [4]:
# Elementweise: 
#A_2=A*A
#A_2
#'Matrixmultiplikation'
A_2=np.dot(A,A)
A_2

array([[2551550, 2581594, 2649540, ..., 2638139, 2556014, 2517071],
       [2516667, 2661555, 2665765, ..., 2630269, 2629727, 2636524],
       [2488295, 2567986, 2576173, ..., 2604318, 2541903, 2568293],
       ...,
       [2539198, 2617183, 2626908, ..., 2659816, 2656003, 2590506],
       [2567293, 2687857, 2674182, ..., 2695988, 2650615, 2567575],
       [2484168, 2550034, 2571237, ..., 2560346, 2550382, 2508835]],
      dtype=int64)

Calculate $A^{10}$

In [16]:
# Elementweise: 
#A_10=np.power(A,10)

#'Matrixmultiplikation'
A_10=np.linalg.matrix_power(A,10)
A_10

array([[-3217934679397191671,    39502435647437911, -1845890943948993953,
        ...,  5361655430007329588, -5175522843994758972,
        -1189568380649105445],
       [ 1775742296015718345,  4619258476781510797, -7192022787231966400,
        ..., -5440291100557217238,  -999204664930835185,
         7953187465045441565],
       [ 3831009398021769021, -2324146115957668751, -4121230203714238290,
        ..., -3949525212110823546, -7629642854375689322,
          753242152589399803],
       ...,
       [-3515658889769646984, -8896070117809915354, -8416495727443977825,
        ...,  2402027721995730783, -3496599086736348648,
        -8545537457781032756],
       [-1547116487059143444, -5640855832830312937,  3927539588894879072,
        ..., -8523279653311344304,   324602177110034036,
         6185695849293574663],
       [-6880697318010437640,  7301900279990194082,  6183489416441471549,
        ..., -4807375086383978646, -5994800311882934826,
        -6656638004291657914]], dtype=int64)

Calculate $A · B$

In [18]:
AB=np.dot(A,B)
AB

array([[2055161, 2050951, 1972436, ..., 2065014, 2060982, 1984139],
       [2118281, 2049247, 2015676, ..., 2102381, 2100491, 1979135],
       [2031533, 2001334, 1993409, ..., 2044321, 2073806, 1957136],
       ...,
       [2078378, 2059793, 2034957, ..., 2136328, 2143351, 2005255],
       [2062547, 2092637, 2062358, ..., 2177131, 2175299, 2057610],
       [2007712, 1995773, 1928060, ..., 2021839, 2074237, 1925888]],
      dtype=int64)

Calculate $(A · B)^{−1}$

In [28]:
AB_inv=np.linalg.inv(np.dot(A,B))
AB_inv

array([[-2.87109429e-03, -6.79477695e-03, -7.83252398e-05, ...,
        -1.70589216e-03, -2.06970616e-03,  3.08607246e-03],
       [-4.05978041e-03, -9.95608738e-03, -3.33974770e-04, ...,
        -2.08090261e-03, -3.03200344e-03,  3.98875684e-03],
       [-4.02364942e-03, -9.61042590e-03, -7.46264908e-05, ...,
        -2.42851135e-03, -2.91861559e-03,  4.37844195e-03],
       ...,
       [ 4.26308821e-03,  9.95661667e-03, -1.45778751e-04, ...,
         2.90716327e-03,  3.01438428e-03, -5.08509007e-03],
       [-3.07662180e-03, -7.12031513e-03,  2.49325787e-05, ...,
        -2.01968711e-03, -2.15228353e-03,  3.50529790e-03],
       [-8.07553135e-05, -1.08822806e-04,  3.29101122e-05, ...,
        -1.24153352e-04, -2.88291012e-05,  1.69406401e-04]])

Calculate $spur(A)$

In [31]:
#numpy command
spur=np.trace(A)
print(spur)


#manual with matrix diagonal
print(np.sum(A.diagonal()))
#manual with for loop
spur_manual=0
for i in range(0,A.shape[0]):
    spur_manual+=A[i,i]
print(spur_manual)

51155
51155
51155


Calculate $det(A)$

In [5]:
import math
print(np.linalg.det(A))
#--> obviously a problem occours. Read numpy documentation

#use slogdet function instead
print(np.linalg.slogdet(A))
math.exp(6319)

C:\Users\Fabian\anaconda3\envs\Uebung\lib\site-packages\numpy\linalg\linalg.py:2159: RuntimeWarning: overflow encountered in det
  r = _umath_linalg.det(a, signature=signature)


-inf
(-1.0, 6319.805367928768)


OverflowError: math range error