<img src="KITlogo_1c_deutsch-eps-converted-to.pdf" width="200" height="200" align="right"/>

##### Lehrstuhl für Analytics and Statistics (IOR)
##### Prof. Dr. Oliver Grothe
##### WS 2021

# Analyse multivariater Daten
## Übung 8


In [17]:
import pandas as pd
import numpy as np
from scipy.stats import t
from numpy import linalg
import scipy
import seaborn as sns
import statsmodels.api as sm
from statsmodels.formula.api import ols
#!pip install seaborn --upgrade
import matplotlib.pyplot as plt
# Plotting
plt.rcParams['figure.figsize'] = [12, 9]
sns.set(style='darkgrid')

# Warnungen unterdrücken
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

## Aufgabe 4
Dateneingabe

In [13]:
margarine = np.array([[68, 1,1],
                       [64, 1,1],
                       [65 ,1,1],
                       [66, 1,1],
                       [63, 1,1],
                       [59 ,1,1],
                       [59, 1,1],
                       [64 ,1,1],
                       [67, 1,1],
                       [63,1,1],
             [59 ,2,1],
             [ 49 ,2,1],
             [ 50 ,2,1],
             [ 50 ,2,1],
             [ 51 ,2,1],
             [ 52 ,2,1],
             [ 48,2,1],
             [ 53,2,1],
              [53 ,2,1],
             [ 50,2,1],
             [40 ,3,1],
             [ 35 ,3,1],
             [ 39 ,3,1],
             [ 34 ,3,1],
             [ 35 ,3,1],
             [ 38 ,3,1],
             [ 36 ,3,1],
             [ 39,3,1],
              [37 ,3,1],
             [ 36,3,1],
             [59 ,1,2],
             [ 51 ,1,2],
             [ 57 ,1,2],
             [ 52 ,1,2],
             [ 54 ,1,2],
             [ 55 ,1,2],
             [ 56,1,2],
             [ 54 ,1,2],
             [ 53 ,1,2],
             [ 52,1,2],
             [51 ,2,2],
             [ 50 ,2,2],
              [45 ,2,2],
             [ 47 ,2,2],
              [46 ,2,2],
             [ 46 ,2,2],
             [ 48, 2,2],
             [ 45, 2,2],
             [ 49 ,2,2],
             [ 47,2,2],
             [47 ,3,2],
             [ 49 ,3,2],
             [ 39 ,3,2],
             [ 44 ,3,2],
              [40 ,3,2],
              [48 ,3,2],
              [46 ,3,2],
              [47, 3,2],
              [45,3,2],
              [44,3,2]])
df=pd.DataFrame(margarine,columns=['Value','Preis','Kommunikation'])
df

Value  Preis  Kommunikation
0      68      1              1
1      64      1              1
2      65      1              1
3      66      1              1
4      63      1              1
5      59      1              1
6      59      1              1
7      64      1              1
8      67      1              1
9      63      1              1
10     59      2              1
11     49      2              1
12     50      2              1
13     50      2              1
14     51      2              1
15     52      2              1
16     48      2              1
17     53      2              1
18     53      2              1
19     50      2              1
20     40      3              1
21     35      3              1
22     39      3              1
23     34      3              1
24     35      3              1
25     38      3              1
26     36      3              1
27     39      3              1
28     37      3              1
29     36      3              1
30     59      1              2
31     51      1              2
32     57      1              2
33     52      1              2
34     54      1              2
35     55      1              2
36     56      1              2
37     54      1              2
38     53      1              2
39     52      1              2
40     51      2              2
41     50      2              2
42     45      2              2
43     47      2              2
44     46      2              2
45     46      2              2
46     48      2              2
47     45      2              2
48     49      2              2
49     47      2              2
50     47      3              2
51     49      3              2
52     39      3              2
53     44      3              2
54     40      3              2
55     48      3              2
56     46      3              2
57     47      3              2
58     45      3              2
59     44      3              2

In [14]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

#perform two-way ANOVA
model = ols('Value ~ C(Preis) + C(Kommunikation) + C(Preis):C(Kommunikation)', data=df).fit()
sm.stats.anova_lm(model, typ=2)

sum_sq    df           F        PR(>F)
C(Preis)                   3297.900000   2.0  224.629919  6.702551e-27
C(Kommunikation)             52.266667   1.0    7.120081  1.004304e-02
C(Preis):C(Kommunikation)   803.033333   2.0   54.697023  1.040527e-13
Residual                    396.400000  54.0         NaN           NaN

## Aufgabe 5
Bestimmen Sie Eigenwerte und Eigenvektoren der Matrix $A$

In [15]:
A=np.array([[3,-1,-1],[-1,3,1],[-1,1,5]])
A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [-1,  1,  5]])

In [18]:
ew,ev = linalg.eig(A)

In [19]:
ew

array([6., 2., 3.])

In [20]:
ev

array([[-4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
       [ 4.08248290e-01,  7.07106781e-01, -5.77350269e-01],
       [ 8.16496581e-01, -1.27652686e-16,  5.77350269e-01]])

In [26]:
B=np.dot(ev.T,A)

In [27]:
np.dot(B,ev)

array([[ 6.00000000e+00,  1.59507816e-15,  1.23742931e-15],
       [ 1.31427776e-15,  2.00000000e+00, -4.10823025e-16],
       [ 9.15855623e-16, -6.65190147e-16,  3.00000000e+00]])